### ISSUE TITLE
Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#1244]
There have been intermittent test failures with the error `Error: end of central directory record signature not found`. @ktuite and I have seen the error locally, and we also sometimes see the error on CircleCI. The error has been mentioned on the forum: https://forum.getodk.org/t/error-end-of-central-directory-record-signature-not-found/36182

We've seen two versions of the error:

Version 1:
```
     Error: end of central directory record signature not found
      at node_modules/yauzl/index.js:183:14
      at Immediate.<anonymous> (node_modules/yauzl/index.js:615:38)
      at processImmediate (internal/timers.js:464:21)
```

Version 2:
```
     Error: end of central directory record signature not found
      at node_modules/yauzl/index.js:183:14
      at node_modules/yauzl/index.js:622:5
      at node_modules/fd-slicer/index.js:32:7
      at FSReqCallback.wrapper [as oncomplete] (fs.js:561:5)
```

Version 1 of the error can be seen in [this](https://app.circleci.com/pipelines/github/getodk/central-backend/906/workflows/f5b0b5a8-f428-4435-8fca-32bac5814a41/jobs/1653) CircleCI build. I ran `make test` in CircleCI [200 times](https://github.com/getodk/central-backend/issues/588#issuecomment-1235669602), and the error came up 6 times (all version 1). In CircleCI, we have seen the error in the following tests:

<details>
<summary>List</summary>

```
  1) zipPart streamer
       should close the archive only after parts are finalized:

  1) managed encryption
       end-to-end
         should decrypt attached files successfully:

  2) managed encryption
       end-to-end
         should handle mixed [plaintext/encrypted] attachments (not decrypting):

  1) .zip attachments streaming
       should stream the contents to files at the appropriate paths:

  1) api: /forms/:id/submissions
       [draft] .csv.zip
         should not carry over drafts when a draft is replaced:
```
</details>

@ktuite [mentioned](https://github.com/getodk/central-backend/pull/583#issuecomment-1230701615):

> I occasionally see this ` Error: end of central directory record signature not found` error on submission zip tests. Not all the time, not always the same test. But the tests all involve `yauzl`.

@ktuite has seen version 1 of the error in the following test:

```
  1) api: /forms/:id/submissions
       [draft] .csv.zip
         should return draft submissions:
```

I've seen version 2 of the error locally in the following tests:

<details>
<summary>List</summary>

```
  2) managed encryption
       end-to-end
         should decrypt over cookie auth with passphrases provided via url-encoded POST body:

  1) managed encryption
       end-to-end
         should strip .enc suffix from decrypted attachments:

  1) managed encryption
       end-to-end
         should decrypt attached files successfully:

  2) managed encryption
       end-to-end
         should decrypt to CSV successfully:

  1) zipPart streamer
       should close the archive only after parts are finalized:

  2) .csv.zip briefcase output @slow
       should output all rows:

  1) .csv.zip briefcase output @slow
       should attach attachments information if present:

  1) api: /forms/:id/submissions
       .csv.zip GET
         versioning
           should return original instanceId and latest attached audit log when instanceId deprecated with new audit log:

  1) api: /forms/:id/submissions
       .csv.zip GET
         should return consolidated client audit log filtered by user:

  1) api: /forms/:id/submissions
       .csv.zip GET
         should return consolidated client audit log filtered by review state:

  1) api: /forms/:id/submissions
       .csv.zip GET
         should not include data from other forms:

  1) api: /forms/:id/submissions
       [draft] .csv.zip
         should not carry draft submissions forward to the published version upon publish:
```
</details>

The error mentioned on the forum is also version 2 of the error.

**Comment by alxndrsn** [comment]
Closing - old and probably fixed.  Please re-open if seen again.
